import { gl as glAsset } from '../lib/assets';

/*
 * Which textures dress the helmet shell.
 *  - 'contour': our own livery (public/assets/helmet, generated by scripts/make-livery.mjs): the site's
 *    contour field in the site's colours, plus a flat normal map. These are published with the site.
 *  - anything else: the original site's livery files under public/orig (local study only, never
 *    committed); dev builds can look at them with ?variant=<folder>.
 */
export const OWN_LIVERY = 'contour';
// cartoon version: the same livery with ink lines, drawn with cel shading (toonMaterial.js)
export const TOON_LIVERY = 'toon';
export const ORIGINAL_LIVERIES = ['gold', 'lime', 'dark', 'google', 'grid', 'disco'];

export function pickLivery() {
  const forced = import.meta.env.DEV ? new URLSearchParams(location.search).get('variant') : null;
  return ORIGINAL_LIVERIES.includes(forced) || forced === OWN_LIVERY || forced === TOON_LIVERY ? forced : TOON_LIVERY;
}

/** Texture URLs for a livery (shell and visor). `own` tells the renderers the maps are ours (no shell roughness / metallic maps). */
export function helmetMaps(livery) {
  if (livery === OWN_LIVERY || livery === TOON_LIVERY) {
    const toon = livery === TOON_LIVERY;
    return {
      own: true, toon,
      base: toon ? '/assets/helmet/livery-toon.webp' : '/assets/helmet/livery-contour.webp', normal: '/assets/helmet/normal-flat.png',
      // the visor: black with a lime sun strip (scripts/make-visor.mjs); its normal map is flat too
      glassBase: '/assets/helmet/visor-base.webp', glassRoughness: '/assets/helmet/visor-roughness.png', glassNormal: '/assets/helmet/normal-flat.png',
      matcap: '/assets/helmet/matcap-plastic.png', // the clear plastic parts (scripts/make-matcap.mjs)
    };
  }
  return {
    own: false,
    base: glAsset(`textures/helmet/webp/${livery}/Norris_Helmet_mat_BaseColor.webp`),
    normal: glAsset('textures/helmet/webp/Norris_Helmet_mat_Normal.webp'),
    roughness: glAsset('textures/helmet/webp/Norris_Helmet_mat_Roughness.webp'),
    metallic: glAsset('textures/helmet/webp/Norris_Helmet_mat_Metallic.webp'),
    glassBase: glAsset('textures/glass/webp/Norris_Glass_mat_BaseColor.webp'),
    glassRoughness: glAsset('textures/glass/webp/Norris_Glass_mat_Roughness.webp'),
    glassNormal: glAsset('textures/glass/webp/Norris_Glass_mat_Normal.webp'),
    matcap: glAsset('textures/plastic/plastic__matcap-02.webp'),
  };
}
